### ISSUE TITLE
support eslint 2.0.0

### ISSUE THREAD

**Issue by blackjid** [houndci/eslint#18]
A new version of eslint was released http://eslint.org/blog/2016/02/eslint-v2.0.0-released

As this hound service is still in beta, maybe is a good timing to move to eslint `2.0.0`

**Comment by kaelig** [comment]
+1

**Comment by DrBoolean** [comment]
+1

**Comment by frozenfung** [comment]
+1, thanks bro.

**Comment by gylaz** [comment]
Since one of our dependencies [`eslint-config-littlebits`](https://github.com/littlebits/code-standards-js) doesn't support ESLint 2 yet, we can't upgrade in Hound.

**Comment by sch** [comment]
Sorry all 😬 — this should be cleared up with #24 

I would love to look further into a way to augment hound's eslint service without tying it to specific presets. If anyone has any ideas, don't hesitate to reach out — in the meantime, I will do some research.

**Comment by kaelig** [comment]
Thank you!

**Comment by kaelig** [comment]
Thank you @gylaz !
