### ISSUE TITLE
Hound is complaining about invalid eslintrc, but eslint works fine when running on local machine

### ISSUE THREAD

**Issue by nhoffmann** [houndci/eslint#19]
All of a sudden, we are getting this error message from hound:  

> hound — Error parsing config for: eslint. Click "details" for assistance."

Running eslint on a local machine lints fine with our config, so it's not reproducable on our end.

This is our eslintrc: 
https://gist.github.com/nhoffmann/0862258c5e993ddb09c2

Is there something we can do to make eslint run on our local machines in a way that hound is using it, so we can reproduce these errors?

**Comment by kaelig** [comment]
C-style comments (`//`) are not valid in JSON.

**Comment by kaelig** [comment]
@nhoffmann if you need comments inside your config, I recommend using a YAML file instead.

**Comment by nhoffmann** [comment]
@kaelig Thanks

**Comment by islemaster** [comment]
Hi there!  I'm experiencing this same error message, but I'm using a JavaScript config file which should allow C-style comments.  Does Hound not support JavaScript ESLint config files?

* [Our .hound.yml](https://github.com/code-dot-org/code-dot-org/blob/enable-hound-eslint/.hound.yml)
* [Our .eslintrc.js](https://github.com/code-dot-org/code-dot-org/blob/enable-hound-eslint/.eslintrc.js)
