### ISSUE TITLE
.eslintrc configuration file format

### ISSUE THREAD

**Issue by hpurmann** [houndci/eslint#26]
I tried enabling HoundCI in one of my company's projects. When [testing it](https://github.com/actano/yourchoice/pull/9), I get
```
Error parsing config for: eslint. Click "details" for assistance.
```

Is it possible that Hound does not support all configuration file formats? We are using `.eslintrc.json` instead of the [deprecated `.eslintrc`](http://eslint.org/docs/user-guide/configuring#configuration-file-formats).

On first glance, it [looks like you are only parsing `eslintrc`](https://github.com/houndci/eslint/blob/1f53e3249d87a8020ba6ff591fcf73753f75df53/lib/config.js#L18) (though I don't know where the prefix-dot comes into play). Is this true?

**Comment by timaschew** [comment]
Maybe the issue is that you using eslint 2.x
Because I used a `.eslintrc` file I got the same error.

See https://github.com/houndci/eslint/issues/18
Unfortunately it doesn't work even with eslint 1.x 😢 see https://github.com/houndci/eslint/issues/27
