### ISSUE TITLE
Add other plugin names to whitelist?

### ISSUE THREAD

**Issue by ahoym** [houndci/eslint#32]
Hello,

I noticed you guys keep a whitelist of `eslint-plugins-*`. In this commit https://github.com/houndci/eslint/commit/32592101293915ae041180caa632cc2810371766 you introduced a lot of other `eslint-plugins` but didn't update the whitelist.

I think we need add the following [to here][0]:
+ `"import"`
+ `"jsx-a11y"`
+ `"promise"`

[0]: https://github.com/houndci/eslint/blob/master/lib/config.js#L7-L10

**Comment by ahoym** [comment]
Sorry, github shortcut typo. Will update this with a description and edit the title soon

**Comment by tkwidmer** [comment]
👍 Need this.
