### ISSUE TITLE
Hound is unable to resolve path to module while local ESLint works

### ISSUE THREAD

**Issue by kpalmvik** [houndci/eslint#34]
In one of our repos we get `Unable to resolve path to module '[MODULE]'.` errors from Hound, while the local installation of ESLint lints the same files without any error.

To demonstrate the issue I created a dummy repo with a minimal configuration that matches what we use, and a PR where Hound barks while my local ESLint is happy: https://github.com/kpalmvik/hound-test/pull/1

Any idea if this is an issue with Hound or the configuration?

**Comment by ahoym** [comment]
@kpalmvik, I'm also experiencing the same problem, and I think it's an issue with Hound.

See my PR against this repo for details: https://github.com/houndci/eslint/pull/36

**Comment by kpalmvik** [comment]
@gylaz: Just to clarify, was this and #32 closed because `no-unresolved` cannot be supported by Hound right now, as indicated in [the PR comment ](https://github.com/houndci/eslint/pull/36#issuecomment-226909675) by @thorncp?

**Comment by gylaz** [comment]
This is closed because ESLint is now part of the https://github.com/houndci/linters repo. A lot of work has been recently done to ESLint, since it's still in beta. If you are still experiencing this problem, please file an issue in the `linters` repo.
